### ISSUE TITLE
Plan for Libm

### ISSUE THREAD

**Issue by musm** [JuliaMath/Libm.jl#54] opened 2016-10-05 02:53 UTC
Here is the plan (upon discussions with @ChrisRackauckas )
- Pull out  the Sleef submodule to  Sleef.jl package  (it’s feature complete for Float32/Float64)
- Pull out  the Musl and Cephes submodule to  Musl.jl and Cephes.jl package  (very few functions have been ported, but do this nonetheless, as others may want to help adding functions)
- Rename Libm.jl to Amal.jl (my name for the new Julia math library, Amal for "amalgamation" of the best open source math libraries). Amal.jl will have native support for Float16 and in the future  hopefully will also support Float80/128. In other words, Amal.jl is my hope for the future Julia Libm.
- Create LibmBenchmarks.jl that basically REQUIRES  each of these packages and holds testing and benchmarking functions. 

_In the future Sleef.jl, Musl.jl, Cephes.jl will probably be deprecated. But for the present it could be useful to have them in separate repos for testing purposes._

The disadvantage of having them all as submodules is method redefinitions. And that right now Libm.jl is a mess with 4 submodules.

@ViralBShah

**Comment by ChrisRackauckas** [comment] 2016-10-05 03:33
Just to chime in with the other parts of the discussion:
- The reason for a Sleef.jl package is that it's a feature-complete port which will be useful for benchmarking against (we like to show Julia is good!). 
- Having everything as submodules and having the benchmarking as part of the main package means that the main package has a lot of bloat. You just want the best implementations for each function, not four implementations of each. Moving the benchmarking out means that only the benchmarks requires the different implementations, which is much more sane.
- At first, I was against the Amal.jl idea. I thought Libm.jl should be a metapackage which re-exports the "best" functions from each library, building a complete Libm, with Amal.jl being @musm + other's new Julia implementations. But with the pace @musm and the rest of the Julia community is going, it won't be very long until Libm.jl would just be re-exporting this Amal.jl for many reasons (first of all because it's putting together the best features of each library, tailor made to benchmark faster on Julia, and will support more Julia types).
- So why Amal.jl instead of Libm.jl? @musm is putting the work in, so why not let him name it?

**Comment by vchuravy** [comment] 2016-10-05 03:41
I agree that we should move the Sleef, musl, and Cephes ports out into their own packages. Libm.jl should be a curated (and opinionated) package containing the best possible implementation under the trade-offs we care for. 

Whether the package is called Libm or Amal I have no preferred way, but Libm has the clear recognisable name going for it. Having a separate benchmark package might also be helpful.

**Comment by musm** [comment] 2016-10-05 03:55
@vchuravy interesting on the gpu throughput of the div instruction. On my haswell  a division  10-24 times the throughput of a single multiply.

**Comment by oxinabox** [comment] 2016-10-05 04:40
I think Libm.jl is a good name for this package, that has the best of breed functions.
It says "Julia Math Library" and that is what this is.

I think mantaining Julia implementations of Sleef (etc), is rather excessive.
No one should want to use them except for benchmarking, and even that is limitted.
Libm.jl (or Amal.jl), should for most purposes be Benchmarking against past versions of itself -- that is how to check for performance regressions.

I think it is worth snapshotting the current version with a Git tag, for anyone who really wants to do that benchmark.
But i question the worth of maintaining it, thus I don't really see any point of having a repo, rather than a tag, or at most a branch. 
Obviously, that is the call of who ever maintains it though.
So if @musm feels the desire to ensure that it keeps working with all versions of julia, then that is their game. But since @musm is already talking about deprecating them... 

WRT naming, I am maintaining a Julia Wapper of the original C code for SLEEF.
Currently called [SLEEF.jl](https://github.com/oxinabox/SLEEF.jl)
It exists primarily just for purposes of benchmarking against*
And so is not a registered package.
I'm happy to rename that if desired.
Perhaps SLEEF_wrapper.jl

It is worth benchmarking against things that 3rd party to Libm.jl.
Like the C sleef code. Like the C openlibm etc.
Because that is interesting to users.
It is not interesting to users to know how it benchmarks against worse algorithms, written/ported by same people.
It is only interesting to developers, _once_.
After that point you switch to the best, then never touch the old one again,
(more or less)

\* answer wrt benchmarking: Pure Julia sleef significantly beats ccalling SLEEF even when ccalling the SIMD optimised versions. Theory goes that this is because ccall can not be inlined, and because automatic SIMD with LLVM IR works _excellently_ on julia code.

**Comment by ChrisRackauckas** [comment] 2016-10-05 04:44
I really don't think it would be difficult to maintain. It's not like it has any dependencies: it's pretty much just the most basic Julia code. Anything that it uses would likely be fixed with a simple regex find/replace.

**Comment by musm** [comment] 2016-10-05 04:52
Git branches sounds like a bad idea since you can't have two things at once and compare them. Benchmarks in the readme are vs openlibm.

I can also move Sleef.jl, Musl.jl, Cephes.jl, LibmBenchmarks.jl to a personal repo if people are opposed to having  modules that will likely be little used and more for dev purposes. But it would be nice to have them public, in this org so other can contribute. We also don't have to tag them.

**Comment by ChrisRackauckas** [comment] 2016-10-05 04:55
Agreed. You shouldn't have to checkout branches while benchmarking. Not only would that likely mess with precompilation, and branches can be even harder to maintain than a separate repository. Might as well also have the issues specific to the right codes.

**Comment by ViralBShah** [comment] 2016-10-05 05:00
+1 to separate repos for each of these.

**Comment by ViralBShah** [comment] 2016-10-05 05:10
Is it worth also separating the tests into their own package - LibMTests.jl - so that these tests can be uniformly applied to all the packages?

**Comment by simonbyrne** [comment] 2016-10-05 10:28
Probably a good idea to split out the tests (so we can use it on other libms). I don't really mind about packages vs submodules; what's the issue with redefinitions?

**Comment by dpsanders** [comment] 2016-10-06 11:59
Just a comment about naming. Libm is clear only for people coming from a low level C background. Even the C header file is called math.h

I would suggest a name more along the lines of Math.jl  or similar that actually conforms to the Julia package naming policy and describes the package.

**Comment by musm** [comment] 2016-10-06 15:32
@dpsanders  ......In c there are many different libms that declare the  common math functions as specified by the  C Standard Library/C++ Standard Library, which are found in the math.h/cmath.h headers.

Standard library implementations (which include math headers):  (ie. each define their own math.h/cmath.h): glibc, musl, BSD libc, dietlibc

Libm only library implementations: msun, fdlibm, openlibm, intel libm

Specialized math libraries include: Cephes, SLEEF, yeppp! (not a very usable libm since it doesn't have many basic functions), mpfr, crlibm, arb

**Closed as completed** 2016-10-12 19:09 UTC
